name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run Maven build and tests
        run: mvn clean install

      - name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports